ENABLE_LANE_DETECTION = True
ENABLE_SIGN_DETECTION = True
ENABLE_FRONTAL_ULTRASONIC = True


BASE_SPEED = 5
#LOW_SPEED = BASE_SPEED / 2
LOW_SPEED = 3

# SIGNS
CROSSWALK_EXECUTION_DURATION = 5
STOP_DURATION = 3
PARKING_SPEED = 10

# FRAMES PARAMS
LANES_FPS = 1
SIGNS_FPS = 3

